# Generated by Django 5.2.3 on 2025-07-01 22:52

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(default=books.models._hex_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('pages', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['title'],
            },
        ),
    ]
